# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Swift using Swiftly
      run: |
        # Download Swiftly package
        curl -O https://download.swift.org/swiftly/darwin/swiftly.pkg
        # Install to the current user's home directory to avoid permission issues
        installer -pkg swiftly.pkg -target CurrentUserHomeDirectory
        # Initialize Swiftly in the user's environment
        ~/.swiftly/bin/swiftly init --quiet-shell-followup
        source ~/.swiftly/env.sh
        # Install Swift 6.1
        swiftly install 6.1
        # Verify installation
        swift --version
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
